name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ✅ Login to ACR
      - name: Docker Login to ACR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_LOGIN_SERVER }}

      # ✅ Deploy to Production WebApp
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: sit722-prod-app   # ⚠️ create this in Azure Portal
          images: ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest

      # ✅ Smoke test production health
      - name: Run Smoke Test
        run: curl -f https://sit722-prod-app.azurewebsites.net/health
