name: Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Azure Login with Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Deploy container image to WebApp
      - name: Deploy to Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: sit722-prod-app
          images: ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest

      # Run acceptance test
      - name: Run Acceptance Tests
        run: curl -f https://sit722-prod-app.azurewebsites.net/health
