name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/sit722-app sit722-app=<your-registry>.azurecr.io/sit722-app:${{ github.sha }}